name: wander_nest
description: "A new Flutter project."
publish_to: 'none'
version: 1.1.0+2

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1

  freezed_annotation: ^2.0.0
  json_annotation: ^4.9.0
  http: ^1.4.0
  flutter_riverpod: ^2.6.1 
  flutter_map: ^8.1.1
  latlong2: ^0.9.1
  flutter_staggered_animations: ^1.1.1
  flutter_map_cancellable_tile_provider: ^3.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  freezed: ^2.0.0
  build_runner: ^2.4.7
  json_serializable: ^6.0.0
  mockito: ^5.4.6

flutter:
  uses-material-design: true
